<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.ani.rnec.gov.co/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ws.ani.rnec.gov.co/" name="WSConsultas">
<types>
<xsd:schema>
<xsd:import namespace="http://ws.ani.rnec.gov.co/" schemaLocation="http://10.20.0.15/registraduria/aniwsV2/WSConsultas?xsd=1" />
</xsd:schema>
</types>
<message name="cambiarContrasena">
<part name="parameters" element="tns:cambiarContrasena" />
<part name="ip" element="tns:ip" />
<part name="contrasena" element="tns:contrasena" />
<part name="usuario" element="tns:usuario" />
</message>
<message name="cambiarContrasenaResponse">
<part name="result" element="tns:cambiarContrasenaResponse" />
</message>
<message name="consultarCedulas">
<part name="parameters" element="tns:consultarCedulas" />
<part name="ip" element="tns:ip" />
<part name="contrasena" element="tns:contrasena" />
<part name="usuario" element="tns:usuario" />
</message>
<message name="consultarCedulasResponse">
<part name="result" element="tns:consultarCedulasResponse" />
</message>
<portType name="WSConsultas">
<operation name="cambiarContrasena" parameterOrder="parameters ip contrasena usuario">
<input wsam:Action="http://ws.ani.rnec.gov.co/WSConsultas/cambiarContrasenaRequest" message="tns:cambiarContrasena" />
<output wsam:Action="http://ws.ani.rnec.gov.co/WSConsultas/cambiarContrasenaResponse" message="tns:cambiarContrasenaResponse" />
</operation>
<operation name="consultarCedulas" parameterOrder="parameters ip contrasena usuario">
<input wsam:Action="http://ws.ani.rnec.gov.co/WSConsultas/consultarCedulasRequest" message="tns:consultarCedulas" />
<output wsam:Action="http://ws.ani.rnec.gov.co/WSConsultas/consultarCedulasResponse" message="tns:consultarCedulasResponse" />
</operation>
</portType>
<binding name="WSConsultasPortBinding" type="tns:WSConsultas">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
<operation name="cambiarContrasena">
<soap:operation soapAction="" />
<input>
<soap:body use="literal" parts="parameters" />
<soap:header message="tns:cambiarContrasena" part="ip" use="literal" />
<soap:header message="tns:cambiarContrasena" part="contrasena" use="literal" />
<soap:header message="tns:cambiarContrasena" part="usuario" use="literal" />
</input>
<output>
<soap:body use="literal" />
</output>
</operation>
<operation name="consultarCedulas">
<soap:operation soapAction="" />
<input>
<soap:body use="literal" parts="parameters" />
<soap:header message="tns:consultarCedulas" part="ip" use="literal" />
<soap:header message="tns:consultarCedulas" part="contrasena" use="literal" />
<soap:header message="tns:consultarCedulas" part="usuario" use="literal" />
</input>
<output>
<soap:body use="literal" />
</output>
</operation>
</binding>
<service name="WSConsultas">
<port name="WSConsultasPort" binding="tns:WSConsultasPortBinding">
<soap:address location="http://10.20.0.15/registraduria/aniwsV2/WSConsultas" />
</port>
</service>
</definitions>
