spring:
   profiles: dev,default
   application:
      name: RestRegistraduria
      ip: 10.20.0.15
      password: Password1#
      usuario: UNIDISTRITAL
      key: Pru_UD_public_bin.key
server:
   port: 8080

---
spring: 
   profiles: prod
   application:
      name: RestRegistraduria
      ip: 10.20.0.15
      password: Password1#
      usuario: UNIDISTRITAL
      key: 
server: 
   port: 4431
